spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://39.105.72.56:5432/axis
    username:
    password:

server:
  port: 9090

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xu.axis.model
pagehelper:
  auto-dialect: true
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
